import type { UnitData } from "@/types";

export const UNITS: Record<string, UnitData> = {
  unit1: {
    id: "unit1",
    name: "Pengadang Baru",
    tagline: "Private Pool · Sehingga 15 Orang",
    address: "A 482, Taman Haji Da, Kg Pengadang Baru, 20050 Kuala Terengganu",
    coordinates: { lat: 5.2733947, lng: 103.1034652 },
    maxPax: 15,
    bedrooms: 4,
    heroImage: "/images/unit1/hero-unit1-1.jpeg",
    images: [
      "/images/unit1/pool-unit1-1.jpeg",
      "/images/unit1/exterior-unit1-1.jpeg",
      "/images/unit1/pool-unit1-2.jpeg",
      "/images/unit1/living-unit1-1.jpeg",
      "/images/unit1/living-unit1-2.jpeg",
      "/images/unit1/bedroom-unit1-1.jpeg",
      "/images/unit1/bedroom-unit1-2.jpeg",
      "/images/unit1/bedroom-unit1-3.jpeg",
      "/images/unit1/bedroom-unit1-4.jpeg",
      "/images/unit1/kitchen-unit1-1.jpeg",
      "/images/unit1/kitchen-unit1-2.jpeg",
      "/images/unit1/bathroom-unit1-1.jpeg",
      "/images/unit1/bathroom-unit1-2.jpeg",
      "/images/unit1/bathroom-unit1-3.jpeg",
      "/images/unit1/ruang-indoor-games-1.jpeg",
      "/images/unit1/tempat-letak-kereta-1.jpeg",
      "/images/unit1/exterior-unit1-1.jpeg",
    ],
    pricing: {
      weekday_1night: 550,
      weekday_2night: 1000,
      weekend_1night: 650,
      weekend_2night: 1200,
      holiday_1night: 700,
      holiday_2night: 1300,
    },
  },
  unit2: {
    id: "unit2",
    name: "Bukit Besar",
    tagline: "Bungalow 3 Tingkat · Sehingga 25 Orang",
    address: "No 2, Taman Mutiara, Jln Seri Bayas, 21100 Kuala Terengganu",
    coordinates: { lat: 5.3039, lng: 103.1317 },
    maxPax: 25,
    bedrooms: 5,
    heroImage: "/images/unit2/hero-unit2-1.jpeg",
    images: [
      "/images/unit2/exterior-unit2-1.jpeg",
      "/images/unit2/pool-unit2-1.jpeg",
      "/images/unit2/pool-unit2-2.jpeg",
      "/images/unit2/living-unit2-1.jpeg",
      "/images/unit2/living-unit2-2.jpeg",
      "/images/unit2/living-unit2-3.jpeg",
      "/images/unit2/bedroom-unit2-1.jpeg",
      "/images/unit2/bedroom-unit2-2.jpeg",
      "/images/unit2/bedroom-unit2-3.jpeg",
      "/images/unit2/bedroom-unit2-4.jpeg",
      "/images/unit2/bedroom-unit2-5.jpeg",
      "/images/unit2/bedroom-unit2-6.jpeg",
      "/images/unit2/bathroom-unit2-1.jpeg",
      "/images/unit2/bathroom-unit2-2.jpeg",
      "/images/unit2/bathroom-unit2-3.jpeg",
      "/images/unit2/bathroom-unit2-4.jpeg",
      "/images/unit2/bathroom-unit2-5.jpeg",
      "/images/unit2/kitchen-unit2-1.jpeg",
      "/images/unit2/kitchen-unit2-2.jpeg",
      "/images/unit2/balcony-level-2-1.jpeg",
      "/images/unit2/ruang-makan-1.jpeg",
      "/images/unit2/indoor-games-1.jpeg",
      "/images/unit2/mesin-basuh-1.jpeg",
      "/images/unit2/ruang-tempat-letak-kereta-1.jpeg",
      "/images/unit2/exterior-unit2-1.jpeg",
    ],
    pricing: {
      weekday_1night: 800,
      weekday_2night: 1500,
      weekend_1night: 900,
      weekend_2night: 1700,
      holiday_1night: 1000,
      holiday_2night: 1900,
    },
  },
};

export const DEPOSIT = 300;
export const CHECKIN_TIME = "3:00 PTG";
export const CHECKOUT_TIME = "12:00 TGH";
